version: '3'

services:
  react_ts_birthday:
    build:
      context: React_ts_happybirthday
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - /usr/app/node_modules
      - ./React_ts_happybirthday:/usr/app
